class Book {
    constructor(name, abbr, chapters, index) {
        this.name = name;
        this.abbr = abbr;
        this.chapters = chapters;
        this.index = index;
    }
}

const BIBLE = Object.freeze({
    GENESIS             : 1,
    EXODUS              : 2,
    LEVITICUS           : 3,
    NUMBERS             : 4,
    DEUTERONOMY         : 5,
    JOSHUA              : 6,
    JUDGES              : 7,
    RUTH                : 8,
    FIRST_SAMUEL        : 9,
    SECOND_SAMUEL       : 10,
    FIRST_KINGS         : 11,
    SECOND_KINGS        : 12,
    FIRST_CHRONICLES    : 13,
    SECOND_CHRONICLES   : 14,
    EZRA                : 15,
    NEHEMIAH            : 16,
    ESTHER              : 17,
    JOB                 : 18,
    PSALMS              : 19,
    PROVERBS            : 20,
    ECCLESIASTES        : 21,
    SONG_OF_SOLOMON     : 22,
    ISAIAH              : 23,
    JEREMIAH            : 24,
    LAMENTATIONS        : 25,
    EZEKIEL             : 26,
    DANIEL              : 27,
    HOSEA               : 28,
    JOEL                : 29,
    AMOS                : 30,
    OBADIAH             : 31,
    JONAH               : 32,
    MICAH               : 33,
    NAHUM               : 34,
    HABAKKUK            : 35,
    ZEPHANIAH           : 36,
    HAGGAI              : 37,
    ZECHARIAH           : 38,
    MALACHI             : 39,
    MATTHEW             : 40,
    MARK                : 41,
    LUKE                : 42,
    JOHN                : 43,
    ACTS                : 44,
    ROMANS              : 45,
    FIRST_CORINTHIANS   : 46,
    SECOND_CORINTHIANS  : 47,
    GALATIANS           : 48,
    EPHESIANS           : 49,
    PHILIPPIANS         : 50,
    COLOSSIANS          : 51,
    FIRST_THESSALONIANS : 52,
    SECOND_THESSALONIANS: 53,
    FIRST_TIMOTHY       : 54,
    SECOND_TIMOTHY      : 55,
    TITUS               : 56,
    PHILEMON            : 57,
    HEBREWS             : 58,
    JAMES               : 59,
    FIRST_PETER         : 60,
    SECOND_PETER        : 61,
    FIRST_JOHN          : 62,
    SECOND_JOHN         : 63,
    THIRD_JOHN          : 64,
    JUDE                : 65,
    REVELATION          : 66
});

const Bible = {
    [BIBLE.GENESIS]             : new Book('Genesis',        'Gen',   50,  1),
    [BIBLE.EXODUS]              : new Book('Exodus',         'Exod',  40,  2),
    [BIBLE.LEVITICUS]           : new Book('Leviticus',      'Lev',   27,  3),
    [BIBLE.NUMBERS]             : new Book('Numbers',        'Num',   36,  4),
    [BIBLE.DEUTERONOMY]         : new Book('Deuteronomy',    'Deut',  34,  5),
    [BIBLE.JOSHUA]              : new Book('Joshua',         'Josh',  24,  6),
    [BIBLE.JUDGES]              : new Book('Judges',         'Judg',  21,  7),
    [BIBLE.RUTH]                : new Book('Ruth',           'Ruth',   4,  8),
    [BIBLE.FIRST_SAMUEL]        : new Book('1 Samuel',       '1Sam',  31,  9),
    [BIBLE.SECOND_SAMUEL]       : new Book('2 Samuel',       '2Sam',  24, 10),
    [BIBLE.FIRST_KINGS]         : new Book('1 Kings',        '1Kgs',  22, 11),
    [BIBLE.SECOND_KINGS]        : new Book('2 Kings',        '2Kgs',  25, 12),
    [BIBLE.FIRST_CHRONICLES]    : new Book('1 Chronicles',   '1Chr',  29, 13),
    [BIBLE.SECOND_CHRONICLES]   : new Book('2 Chronicles',   '2Chr',  36, 14),
    [BIBLE.EZRA]                : new Book('Ezra',           'Ezra',  10, 15),
    [BIBLE.NEHEMIAH]            : new Book('Nehemiah',       'Neh',   13, 16),
    [BIBLE.ESTHER]              : new Book('Esther',         'Esth',  10, 17),
    [BIBLE.JOB]                 : new Book('Job',            'Job',   42, 18),
    [BIBLE.PSALMS]              : new Book('Psalms',         'Ps',   150, 19),
    [BIBLE.PROVERBS]            : new Book('Proverbs',       'Prov',  31, 20),
    [BIBLE.ECCLESIASTES]        : new Book('Ecclesiastes',   'Eccl',  12, 21),
    [BIBLE.SONG_OF_SOLOMON]     : new Book('Song of Solomon','Song',   8, 22),
    [BIBLE.ISAIAH]              : new Book('Isaiah',         'Isa',   66, 23),
    [BIBLE.JEREMIAH]            : new Book('Jeremiah',       'Jer',   52, 24),
    [BIBLE.LAMENTATIONS]        : new Book('Lamentations',   'Lam',    5, 25),
    [BIBLE.EZEKIEL]             : new Book('Ezekiel',        'Ezek',  48, 26),
    [BIBLE.DANIEL]              : new Book('Daniel',         'Dan',   12, 27),
    [BIBLE.HOSEA]               : new Book('Hosea',          'Hos',   14, 28),
    [BIBLE.JOEL]                : new Book('Joel',           'Joel',   3, 29),
    [BIBLE.AMOS]                : new Book('Amos',           'Amos',   9, 30),
    [BIBLE.OBADIAH]             : new Book('Obadiah',        'Obad',   1, 31),
    [BIBLE.JONAH]               : new Book('Jonah',          'Jonah',  4, 32),
    [BIBLE.MICAH]               : new Book('Micah',          'Mic',    7, 33),
    [BIBLE.NAHUM]               : new Book('Nahum',          'Nah',    3, 34),
    [BIBLE.HABAKKUK]            : new Book('Habakkuk',       'Hab',    3, 35),
    [BIBLE.ZEPHANIAH]           : new Book('Zephaniah',      'Zeph',   3, 36),
    [BIBLE.HAGGAI]              : new Book('Haggai',         'Hag',    2, 37),
    [BIBLE.ZECHARIAH]           : new Book('Zechariah',      'Zech',  14, 38),
    [BIBLE.MALACHI]             : new Book('Malachi',        'Mal',    4, 39),
    [BIBLE.MATTHEW]             : new Book('Matthew',        'Matt',  28, 40),
    [BIBLE.MARK]                : new Book('Mark',           'Mark',  16, 41),
    [BIBLE.LUKE]                : new Book('Luke',           'Luke',  24, 42),
    [BIBLE.JOHN]                : new Book('John',           'John',  21, 43),
    [BIBLE.ACTS]                : new Book('Acts',           'Acts',  28, 44),
    [BIBLE.ROMANS]              : new Book('Romans',         'Rom',   16, 45),
    [BIBLE.FIRST_CORINTHIANS]   : new Book('1 Corinthians',  '1Cor',  16, 46),
    [BIBLE.SECOND_CORINTHIANS]  : new Book('2 Corinthians',  '2Cor',  13, 47),
    [BIBLE.GALATIANS]           : new Book('Galatians',      'Gal',    6, 48),
    [BIBLE.EPHESIANS]           : new Book('Ephesians',      'Eph',    6, 49),
    [BIBLE.PHILIPPIANS]         : new Book('Philippians',    'Phil',   4, 50),
    [BIBLE.COLOSSIANS]          : new Book('Colossians',     'Col',    4, 51),
    [BIBLE.FIRST_THESSALONIANS] : new Book('1 Thessalonians','1Thess', 5, 52),
    [BIBLE.SECOND_THESSALONIANS]: new Book('2 Thessalonians','2Thess', 3, 53),
    [BIBLE.FIRST_TIMOTHY]       : new Book('1 Timothy',      '1Tim',   6, 54),
    [BIBLE.SECOND_TIMOTHY]      : new Book('2 Timothy',      '2Tim',   4, 55),
    [BIBLE.TITUS]               : new Book('Titus',          'Titus',  3, 56),
    [BIBLE.PHILEMON]            : new Book('Philemon',       'Phlm',   1, 57),
    [BIBLE.HEBREWS]             : new Book('Hebrews',        'Heb',   13, 58),
    [BIBLE.JAMES]               : new Book('James',          'Jas',    5, 59),
    [BIBLE.FIRST_PETER]         : new Book('1 Peter',        '1Pet',   5, 60),
    [BIBLE.SECOND_PETER]        : new Book('2 Peter',        '2Pet',   3, 61),
    [BIBLE.FIRST_JOHN]          : new Book('1 John',         '1John',  5, 62),
    [BIBLE.SECOND_JOHN]         : new Book('2 John',         '2John',  1, 63),
    [BIBLE.THIRD_JOHN]          : new Book('3 John',         '3John',  1, 64),
    [BIBLE.JUDE]                : new Book('Jude',           'Jude',   1, 65),
    [BIBLE.REVELATION]          : new Book('Revelation',     'Rev',   22, 66),

    getBook(name) {
        return Object.values(this).find(book => book.name.toLowerCase() === name.toLowerCase());
    }
};